# Generated by Django 5.0.3 on 2024-04-02 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randomium", "0002_address_postal_code_alter_bank_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="user",
        ),
        migrations.AddField(
            model_name="bank",
            name="users",
            field=models.ManyToManyField(
                related_name="banks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
