# Generated by Django 5.0.3 on 2024-04-02 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randomium", "0003_remove_bank_user_bank_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bank",
            name="users",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="banks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
