# Generated by Django 5.0.3 on 2024-04-02 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randomium", "0004_alter_address_postal_code_alter_bank_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="users",
            field=models.ManyToManyField(
                related_name="banks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
