# Generated by Django 5.0.3 on 2024-04-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("randomium", "0005_alter_bank_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank",
            name="users",
        ),
    ]
